@startuml
title Basic UseCase
left to right direction 
:Main Admin: as Admin
User <|- Admin
rectangle CAS <<extrenal>>
rectangle System {
User --- (Ein UseCase)
(Ein UseCase) --> CAS : delegate
(special Usecase) -|> (Ein UseCase)
(Ein UseCase) .> (Included UserCase):<<include>>
(Extended UseCasse) ..> (Ein UseCase):<<extends>>
}
@enduml