### GET 
http://{{host}}:{{port}}/list/2

### Get by https
https://{{host}}/list/2

### GET Powershell
http://{{host}}:{{port}}/powershell/*


### DELETE
DELETE http://{{host}}:{{port}}/del/2 HTTP/1.1

### POST
POST http://{{host}}:{{port}}/new/ HTTP/1.1
Content-Type: application/json

{
    "data":"Ein Test!"
}

### POST HTTPS
POST https://{{host}}/new/ HTTP/1.1
Content-Type: application/json

{
    "data":"Ein Test!!"
}

### PUT
PUT http://{{host}}:{{port}}/update/ HTTP/1.1
Content-Type: application/json

{
    "data":"Ein Test!!"
}